#define TARMAC 0
#define RUMBLE_STRIP 1
#define CONCRETE 2
#define ROCK 3
#define GRAVEL 4
#define MUD 5
#define SAND 6
#define GRASS 7
#define WATER 8
#define COBBLESTONE 9
#define METAL 10
#define RIDGED 11