#define MELBOURNE 0
#define PAUL_RICARD 1
#define SHANGHAI 2
#define SAKHIR_BAHRAIN 3
#define CATALUNYA 4
#define MONACO 5
#define MONTREAL 6
#define SILVERSTONE 7
#define HOCKENHEIM 8
#define HUNGARORING 9
#define SPA 10
#define MONZA 11
#define SINGAPORE 12
#define SUZUKA 13
#define ABU_DHABI 14
#define TEXAS 15
#define BRAZIL 16
#define AUSTRIA 17
#define SOCHI 18
#define MEXICO 19
#define BAKU_AZERBAIJAN 20
#define SAKHIR_SHORT 21
#define SILVERSTONE_SHORT 22
#define TEXAS_SHORT 23
#define SUZUKA_SHORT 24
#define HANOI 25
#define ZANDVOORT 26
#define IMOLA 27
#define PORTIMAO 28
#define JEDDAH 29